### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by NicoGonzalez94** [MatTejerina/Proyecto-Final#14]
Buenas! como va? encontre algunos comentarios en el codigo,

![image](https://github.com/user-attachments/assets/e6f7a9cd-8ed2-4d4e-99eb-0990fc2112a5)
![image](https://github.com/user-attachments/assets/793d1500-84b6-4406-bdd5-001225028dae)

Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by MatTejerina** [comment]
los comentarios ya fueron eliminados del codigo
