### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by NicoGonzalez94** [MatTejerina/Proyecto-Final#15]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que se muestre el nombre junto con el logo de la pagina.

## Resultado actual

• Se muestra el nombre pero no el logo.

## Captura

![image](https://github.com/user-attachments/assets/805becf0-5566-4bde-8c74-6c532d985af3)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by MatTejerina** [comment]
![image](https://github.com/user-attachments/assets/384ec2a4-46cf-4bb8-91ca-c1b9cfc1c6c0)

El logo ya es visible
